// TEMPORARY DATA

export let role = "admin";

import { TeacherCourse } from "@/types/pagination";

// export const teacherData: TeacherCourse[] = [
//   {
//     teacher: {
//       id: "1",
//       name: "John Smith",
//       birth: new Date("1985-06-15"),
//       email: "john.smith@example.com",
//       phone: "+123456789",
//       ava: "/assets/images/wenjun-lin-.jpg",
//       address: {
//         street: "123 Main St",
//         city: "New York",
//         country: "USA",
//       },
//       more: "Experienced in teaching English and Business Communication.",
//     },
//     course: {
//       id: "1",
//       name: "Advanced English Grammar",
//     },
//     joinDate: new Date("2022-01-10"),
//     kindJob: "Full-time",
//     description:
//       "Teaching advanced grammar concepts to improve students' written and spoken English.",
//     earning: 5000,
//     point: 4.8,
//     status: "Active",
//   },
//   {
//     teacher: {
//       id: "1", // John Smith
//       name: "John Smith",
//       birth: new Date("1985-06-15"),
//       email: "john.smith@example.com",
//       phone: "+123456789",
//       ava: "/assets/images/wenjun-lin-.jpg",
//       address: {
//         street: "123 Main St",
//         city: "New York",
//         country: "USA",
//       },
//       more: "Experienced in teaching English and Business Communication.",
//     },
//     course: {
//       id: "2",
//       name: "Business Communication Skills",
//     },
//     joinDate: new Date("2022-02-01"),
//     kindJob: "Full-time",
//     description: "Focusing on effective communication in business contexts.",
//     earning: 5000,
//     point: 4.8,
//     status: "Active",
//   },
//   {
//     teacher: {
//       id: "2",
//       name: "Emily Johnson",
//       birth: new Date("1990-09-25"),
//       email: "emily.johnson@example.com",
//       phone: "+987654321",
//       ava: "/assets/images/wenjun-lin-.jpg",
//       address: {
//         street: "456 Oak Ave",
//         city: "Los Angeles",
//         country: "USA",
//       },
//       more: "Specializes in teaching IELTS and TOEFL preparation courses.",
//     },
//     course: {
//       id: "3",
//       name: "IELTS Preparation",
//     },
//     joinDate: new Date("2021-05-15"),
//     kindJob: "Part-time",
//     description: "Guiding students through IELTS exam strategies.",
//     earning: 3000,
//     point: 4.9,
//     status: "Active",
//   },
//   {
//     teacher: {
//       id: "2", // Emily Johnson
//       name: "Emily Johnson",
//       birth: new Date("1990-09-25"),
//       email: "emily.johnson@example.com",
//       phone: "+987654321",
//       ava: "/assets/images/wenjun-lin-.jpg",
//       address: {
//         street: "456 Oak Ave",
//         city: "Los Angeles",
//         country: "USA",
//       },
//       more: "Specializes in teaching IELTS and TOEFL preparation courses.",
//     },
//     course: {
//       id: "4",
//       name: "TOEFL Preparation",
//     },
//     joinDate: new Date("2021-06-15"),
//     kindJob: "Part-time",
//     description: "Helping students prepare for the TOEFL exam.",
//     earning: 3000,
//     point: 4.9,
//     status: "Active",
//   },
//   {
//     teacher: {
//       id: "3",
//       name: "Michael Brown",
//       birth: new Date("1978-12-05"),
//       email: "michael.brown@example.com",
//       phone: "+1122334455",
//       ava: "/assets/images/wenjun-lin-.jpg",
//       address: {
//         street: "789 Pine Rd",
//         city: "Chicago",
//         country: "USA",
//       },
//       more: "Over 20 years of experience in teaching Business English.",
//     },
//     course: {
//       id: "5",
//       name: "Business English Communication",
//     },
//     joinDate: new Date("2020-03-22"),
//     kindJob: "Full-time",
//     description: "Teaching professional English communication skills.",
//     earning: 6000,
//     point: 4.7,
//     status: "Active",
//   },
//   {
//     teacher: {
//       id: "3",
//       name: "Michael Brown",
//       birth: new Date("1978-12-05"),
//       email: "michael.brown@example.com",
//       phone: "+1122334455",
//       ava: "/assets/images/wenjun-lin-.jpg",
//       address: {
//         street: "789 Pine Rd",
//         city: "Chicago",
//         country: "USA",
//       },
//       more: "Over 20 years of experience in teaching Business English.",
//     },
//     course: {
//       id: "6",
//       name: "Negotiation Skills in English",
//     },
//     joinDate: new Date("2020-04-01"),
//     kindJob: "Full-time",
//     description: "Teaching negotiation tactics and skills in English.",
//     earning: 6000,
//     point: 4.7,
//     status: "Active",
//   },
//   {
//     teacher: {
//       id: "4",
//       name: "Sarah White",
//       birth: new Date("1982-11-19"),
//       email: "sarah.white@example.com",
//       phone: "+2233445566",
//       ava: "/assets/images/wenjun-lin-.jpg",
//       address: {
//         street: "321 Birch Blvd",
//         city: "Houston",
//         country: "USA",
//       },
//       more: "Expert in teaching conversational English and pronunciation.",
//     },
//     course: {
//       id: "7",
//       name: "English Pronunciation Mastery",
//     },
//     joinDate: new Date("2023-07-01"),
//     kindJob: "Contract",
//     description:
//       "Helping students achieve clear and accurate English pronunciation.",
//     earning: 4000,
//     point: 4.6,
//     status: "Active",
//   },
//   {
//     teacher: {
//       id: "4", // Sarah White
//       name: "Sarah White",
//       birth: new Date("1982-11-19"),
//       email: "sarah.white@example.com",
//       phone: "+2233445566",
//       ava: "/assets/images/wenjun-lin-.jpg",
//       address: {
//         street: "321 Birch Blvd",
//         city: "Houston",
//         country: "USA",
//       },
//       more: "Expert in teaching conversational English and pronunciation.",
//     },
//     course: {
//       id: "8",
//       name: "Conversational English Skills",
//     },
//     joinDate: new Date("2023-08-01"),
//     kindJob: "Contract",
//     description:
//       "Enhancing students' ability to communicate effectively in English.",
//     earning: 4000,
//     point: 4.6,
//     status: "Active",
//   },
//   {
//     teacher: {
//       id: "5",
//       name: "David Lee",
//       birth: new Date("1995-03-08"),
//       email: "david.lee@example.com",
//       phone: "+3344556677",
//       ava: "/assets/images/wenjun-lin-.jpg",
//       address: {
//         street: "654 Maple St",
//         city: "San Francisco",
//         country: "USA",
//       },
//       more: "Focused on teaching online courses for beginners.",
//     },
//     course: {
//       id: "9",
//       name: "Basic English for Beginners",
//     },
//     joinDate: new Date("2022-10-05"),
//     kindJob: "Part-time",
//     description: "Teaching foundational English skills.",
//     earning: 2500,
//     point: 4.5,
//     status: "Active",
//   },
//   {
//     teacher: {
//       id: "5", // David Lee
//       name: "David Lee",
//       birth: new Date("1995-03-08"),
//       email: "david.lee@example.com",
//       phone: "+3344556677",
//       ava: "/assets/images/wenjun-lin-.jpg",
//       address: {
//         street: "654 Maple St",
//         city: "San Francisco",
//         country: "USA",
//       },
//       more: "Focused on teaching online courses for beginners.",
//     },
//     course: {
//       id: "10",
//       name: "English for Kids",
//     },
//     joinDate: new Date("2022-11-01"),
//     kindJob: "Part-time",
//     description: "Teaching English to children using fun and engaging methods.",
//     earning: 2500,
//     point: 4.5,
//     status: "Active",
//   },
// ];

export const PostData = [
  {
    postedUser: "Oohsehun",
    postId: "1",
    type: 1, // Text
    createdDate: new Date("12-10-2024"),
    content: "hello moi nguoi",
  },
  {
    postedUser: "JennieKim",
    postId: "2",
    type: 2, // Image
    createdDate: new Date("12-11-2024"),
    content: "Check out my new photo!",
  },
  {
    postedUser: "LisaManoban",
    postId: "3",
    type: 3, // Video
    createdDate: new Date("12-12-2024"),
    content: "Watch my new dance video!",
  },
  {
    postedUser: "Jisoo",
    postId: "4",
    type: 4, // Link
    createdDate: new Date("12-13-2024"),
    content: "Read this article: https://news.com",
  },
  {
    postedUser: "Oohsehun",
    postId: "5",
    type: 1, // Text
    createdDate: new Date("12-14-2024"),
    content: "It's a great day!",
  },
  {
    postedUser: "Chanyeol",
    postId: "6",
    type: 2, // Image
    createdDate: new Date("12-15-2024"),
    content: "Check out this amazing sunset!",
  },
  {
    postedUser: "Baekhyun",
    postId: "7",
    type: 3, // Video
    createdDate: new Date("12-16-2024"),
    content: "My latest music video is out now!",
  },
  {
    postedUser: "Kai",
    postId: "8",
    type: 4, // Link
    createdDate: new Date("12-17-2024"),
    content: "Here's a cool website: https://coolwebsite.com",
  },
  {
    postedUser: "Rosé",
    postId: "9",
    type: 1, // Text
    createdDate: new Date("12-18-2024"),
    content: "Working on some new music today!",
  },
  {
    postedUser: "D.O.",
    postId: "10",
    type: 2, // Image
    createdDate: new Date("12-19-2024"),
    content: "Look at this delicious meal!",
  },
  {
    postedUser: "Suho",
    postId: "11",
    type: 3, // Video
    createdDate: new Date("12-20-2024"),
    content: "Watch my latest vlog!",
  },
  {
    postedUser: "Lay",
    postId: "12",
    type: 4, // Link
    createdDate: new Date("12-21-2024"),
    content: "Check out this new app: https://newapp.com",
  },
  {
    postedUser: "Lay",
    postId: "13",
    type: 0, // Link
    createdDate: new Date("12-21-2024"),
    content: "Check out this new app: https://newapp.com",
  },
  {
    postedUser: "Lay",
    postId: "14",
    type: 0, // Link
    createdDate: new Date("12-21-2024"),
    content: "Check out this new app: https://newapp.com",
  },
  {
    postedUser: "Lay",
    postId: "15",
    type: 0, // Link
    createdDate: new Date("12-21-2024"),
    content: "Check out this new app: https://newapp.com",
  },
];

export const userData = [
  {
    id: 1,
    fullname: "Nguyễn Văn A",
    birthday: new Date("1995-06-15"),
    gmail: "nguyenvana@gmail.com",
    gender: "Nam",
    phone: "0123456789",
    address: "123 Đường ABC, Quận 1, TP. HCM",
    nickName: "A",
    status: 1,
    job: "Kỹ sư phần mềm",
    bio: "Yêu thích lập trình và công nghệ.",
    hobbies: ["Đọc sách", "Chơi thể thao", "Du lịch"],
    enrolled: new Date("1995-06-15"),
  },
  {
    id: 2,
    fullname: "Trần Thị B",
    birthday: new Date("1992-03-20"),
    gmail: "tranthiB@gmail.com",
    gender: "Nữ",
    phone: "0987654321",
    address: "456 Đường XYZ, Quận 2, TP. HCM",
    nickName: "B",
    status: 0,
    job: "Thiết kế đồ họa",
    bio: "Sáng tạo và đam mê nghệ thuật.",
    hobbies: ["Vẽ tranh", "Chơi guitar"],
    enrolled: new Date("1995-06-15"),
  },
  {
    id: 3,
    fullname: "Lê Văn C",
    birthday: new Date("1988-11-05"),
    gmail: "levanc@gmail.com",
    gender: "Nam",
    phone: "0345678901",
    address: "789 Đường LMN, Quận 3, TP. HCM",
    nickName: "C",
    status: 1,
    job: "Giáo viên",
    bio: "Giáo dục là tương lai.",
    hobbies: ["Đọc sách", "Nghe nhạc"],
    enrolled: new Date("1995-06-15"),
  },
  {
    id: 4,
    fullname: "Phạm Thị D",
    birthday: new Date("1990-07-30"),
    gmail: "phamthid@gmail.com",
    gender: "Nữ",
    phone: "0123456780",
    address: "159 Đường OPQ, Quận 4, TP. HCM",
    nickName: "D",
    status: 1,
    job: "Nghiên cứu viên",
    bio: "Đam mê nghiên cứu khoa học.",
    hobbies: ["Đi bộ", "Yoga"],
    enrolled: new Date("1995-06-15"),
  },
  {
    id: 5,
    fullname: "Nguyễn Quốc E",
    birthday: new Date("1996-01-12"),
    gmail: "nguyenquoce@gmail.com",
    gender: "Nam",
    phone: "0876543210",
    address: "258 Đường RST, Quận 5, TP. HCM",
    nickName: "E",
    status: 0,
    job: "Marketing",
    bio: "Thích làm việc với con người.",
    hobbies: ["Chạy bộ", "Đi du lịch"],
    enrolled: new Date("1995-06-15"),
  },
  {
    id: 6,
    fullname: "Đỗ Minh F",
    birthday: new Date("1993-09-18"),
    gmail: "dominht@gmail.com",
    gender: "Nam",
    phone: "0765432109",
    address: "369 Đường UVW, Quận 6, TP. HCM",
    nickName: "F",
    status: 1,
    job: "Quản lý dự án",
    bio: "Yêu thích quản lý và tổ chức.",
    hobbies: ["Chơi bóng đá", "Xem phim"],
    enrolled: new Date("1995-06-15"),
  },
  {
    id: 7,
    fullname: "Ngô Thị G",
    birthday: new Date("1994-12-25"),
    gmail: "ngothig@gmail.com",
    gender: "Nữ",
    phone: "0654321789",
    address: "456 Đường IJK, Quận 7, TP. HCM",
    nickName: "G",
    status: 0,
    job: "Bác sĩ",
    bio: "Đam mê chăm sóc sức khỏe.",
    hobbies: ["Nấu ăn", "Đi bộ đường dài"],
    enrolled: new Date("1995-06-15"),
  },
  {
    id: 8,
    fullname: "Lê Văn H",
    birthday: new Date("1985-05-22"),
    gmail: "levanh@gmail.com",
    gender: "Nam",
    phone: "0543216789",
    address: "789 Đường ABC, Quận 8, TP. HCM",
    nickName: "H",
    status: 1,
    job: "Luật sư",
    bio: "Yêu thích công lý.",
    hobbies: ["Đọc sách pháp luật", "Chơi cờ"],
    enrolled: new Date("1995-06-15"),
  },
  {
    id: 9,
    fullname: "Trần Văn I",
    birthday: new Date("1989-08-15"),
    gmail: "tranvani@gmail.com",
    gender: "Nam",
    phone: "0321456789",
    address: "321 Đường DEF, Quận 9, TP. HCM",
    nickName: "I",
    status: 1,
    job: "Nhà văn",
    bio: "Sáng tác là cuộc sống.",
    hobbies: ["Viết lách", "Đi du lịch"],
    enrolled: new Date("1995-06-15"),
  },
  {
    id: 10,
    fullname: "Nguyễn Thị J",
    birthday: new Date("1991-10-10"),
    gmail: "nguyenthij@gmail.com",
    gender: "Nữ",
    phone: "0421356789",
    address: "654 Đường GHI, Quận 10, TP. HCM",
    nickName: "J",
    status: 0,
    job: "Nhiếp ảnh gia",
    bio: "Yêu thích chụp hình.",
    hobbies: ["Chụp ảnh", "Du lịch"],
    enrolled: new Date("1995-06-15"),
  },
  {
    id: 11,
    fullname: "Lê Minh K",
    birthday: new Date("1987-04-02"),
    gmail: "leminhk@gmail.com",
    gender: "Nam",
    phone: "0213456789",
    address: "987 Đường STU, Quận 11, TP. HCM",
    nickName: "K",
    status: 1,
    job: "Kỹ sư cơ khí",
    bio: "Thích làm việc với máy móc.",
    hobbies: ["Sửa chữa", "Chơi game"],
    enrolled: new Date("1995-06-15"),
  },
  {
    id: 12,
    fullname: "Nguyễn Thị L",
    birthday: new Date("1998-02-28"),
    gmail: "nguyenthil@gmail.com",
    gender: "Nữ",
    phone: "0112233445",
    address: "135 Đường VWX, Quận 12, TP. HCM",
    nickName: "L",
    status: 1,
    job: "Chuyên viên tài chính",
    bio: "Đam mê số liệu và phân tích.",
    hobbies: ["Đọc sách", "Tập thể dục"],
    enrolled: new Date("1995-06-15"),
  },
];
