// TEMPORARY DATA

export let role = "admin";

export const studentInformationData = [
  {
    id: 1,
    studentName: "Nguyen Van A",
    enrollDate: new Date("2023-01-15"),
    price: 10000000,
    status: 1,
  },
  {
    id: 2,
    studentName: "Tran Thi B",
    enrollDate: new Date("2023-02-20"),
    price: 9500000,
    status: 0,
  },
  {
    id: 3,
    studentName: "Le Van C",
    enrollDate: new Date("2023-03-10"),
    price: 10500000,
    status: 2,
  },
  {
    id: 4,
    studentName: "Pham Thi D",
    enrollDate: new Date("2023-04-25"),
    price: 9800000,
    status: 3,
  },
  {
    id: 5,
    studentName: "Hoang Van E",
    enrollDate: new Date("2023-05-18"),
    price: 11500000,
    status: 1,
  },
  {
    id: 6,
    studentName: "Vu Thi F",
    enrollDate: new Date("2023-06-05"),
    price: 9200000,
    status: 2,
  },
  {
    id: 7,
    studentName: "Nguyen Van G",
    enrollDate: new Date("2023-07-22"),
    price: 11000000,
    status: 1,
  },
  {
    id: 8,
    studentName: "Pham Van H",
    enrollDate: new Date("2023-08-01"),
    price: 9500000,
    status: 3,
  },
  {
    id: 9,
    studentName: "Tran Thi I",
    enrollDate: new Date("2023-09-10"),
    price: 10200000,
    status: 2,
  },
  {
    id: 10,
    studentName: "Le Van J",
    enrollDate: new Date("2023-10-03"),
    price: 10000000,
    status: 1,
  },
  {
    id: 11,
    studentName: "Nguyen Thi K",
    enrollDate: new Date("2023-11-14"),
    price: 9900000,
    status: 1,
  },
  {
    id: 12,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 13,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 14,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 15,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 16,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 17,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 18,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 19,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 20,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 21,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 22,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 23,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 24,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 25,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 26,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 27,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 28,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 29,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 30,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },

  {
    id: 31,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 32,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 33,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 34,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 35,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 36,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 37,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 38,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 39,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 40,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
  {
    id: 41,
    studentName: "Hoang Thi L",
    enrollDate: new Date("2023-12-21"),
    price: 12000000,
    status: 2,
  },
];

export const sessionData = [
  {
    id: 1,
    startTime: "18:00",
    endTime: "21:00",
    day: new Date("2023-01-15"),
    studyContent:
      "Studied JavaScript fundamentals and ES6 features, focusing on arrow functions, destructuring, and template literals.",
  },
  {
    id: 2,
    startTime: "09:00",
    endTime: "12:00",
    day: new Date("2023-01-16"),
    studyContent:
      "Completed a deep dive into CSS Flexbox and Grid layouts to build responsive web designs.",
  },
  {
    id: 3,
    startTime: "14:00",
    endTime: "17:00",
    day: new Date("2023-01-17"),
    studyContent:
      "Explored React hooks, including useState, useEffect, and useContext, and implemented a simple To-Do app.",
  },
  {
    id: 4,
    startTime: "19:00",
    endTime: "22:00",
    day: new Date("2023-01-18"),
    studyContent:
      "Practiced algorithms, focusing on sorting techniques such as quicksort, mergesort, and bubble sort.",
  },
  {
    id: 5,
    startTime: "10:00",
    endTime: "13:00",
    day: new Date("2023-01-19"),
    studyContent:
      "Started learning Node.js and built a basic REST API using Express.js, handling CRUD operations.",
  },
  {
    id: 6,
    startTime: "15:00",
    endTime: "18:00",
    day: new Date("2023-01-20"),
    studyContent:
      "Worked on MongoDB integration with Node.js using Mongoose, focusing on schema design and database queries.",
  },
  {
    id: 7,
    startTime: "08:00",
    endTime: "11:00",
    day: new Date("2023-01-21"),
    studyContent:
      "Learned about authentication and authorization in web apps, implementing JWT for secure API access.",
  },
  {
    id: 8,
    startTime: "13:00",
    endTime: "16:00",
    day: new Date("2023-01-22"),
    studyContent:
      "Refined my understanding of asynchronous JavaScript with promises, async/await, and error handling.",
  },
  {
    id: 9,
    startTime: "17:00",
    endTime: "20:00",
    day: new Date("2023-01-23"),
    studyContent:
      "Developed a full-stack MERN application, integrating React frontend with Node.js, Express, and MongoDB backend.",
  },
  {
    id: 10,
    startTime: "12:00",
    endTime: "15:00",
    day: new Date("2023-01-24"),
    studyContent:
      "Focused on Git and version control, including branching strategies and collaborative workflows using GitHub.",
  },
];

export const courseData = [
  {
    id: 1,
    courseName: "IELTS Class A",
    teacherName: "Nguyen Van A",
    createDate: new Date("2023-01-15"),
    number: 20,
    status: 1,
  },
  {
    id: 2,
    courseName: "IELTS Class B",
    teacherName: "Nguyen Van B",
    createDate: new Date("2023-02-20"),
    number: 18,
    status: 1,
  },
  {
    id: 3,
    courseName: "TOEIC Class A",
    teacherName: "Tran Thi C",
    createDate: new Date("2023-03-10"),
    number: 25,
    status: 1,
  },
  {
    id: 4,
    courseName: "TOEFL Class A",
    teacherName: "Le Van D",
    createDate: new Date("2023-04-05"),
    number: 15,
    status: 0,
  },
  {
    id: 5,
    courseName: "Business English",
    teacherName: "Pham Thi E",
    createDate: new Date("2023-05-12"),
    number: 22,
    status: 1,
  },
  {
    id: 6,
    courseName: "English for Beginners",
    teacherName: "Vo Van F",
    createDate: new Date("2023-06-18"),
    number: 30,
    status: 0,
  },
  {
    id: 7,
    courseName: "Advanced English Writing",
    teacherName: "Nguyen Thi G",
    createDate: new Date("2023-07-23"),
    number: 10,
    status: 1,
  },
  {
    id: 8,
    courseName: "Conversation Skills",
    teacherName: "Tran Van H",
    createDate: new Date("2023-08-05"),
    number: 28,
    status: 1,
  },
  {
    id: 9,
    courseName: "IELTS Class C",
    teacherName: "Nguyen Van I",
    createDate: new Date("2023-09-12"),
    number: 17,
    status: 0,
  },
  {
    id: 10,
    courseName: "English Grammar 101",
    teacherName: "Le Thi J",
    createDate: new Date("2023-10-02"),
    number: 35,
    status: 1,
  },
  {
    id: 11,
    courseName: "IELTS Class D",
    teacherName: "Hoang Van K",
    createDate: new Date("2023-11-14"),
    number: 12,
    status: 0,
  },
  {
    id: 12,
    courseName: "TOEIC Class B",
    teacherName: "Nguyen Thi L",
    createDate: new Date("2023-12-01"),
    number: 23,
    status: 1,
  },
  {
    id: 13,
    courseName: "TOEFL Class B",
    teacherName: "Pham Van M",
    createDate: new Date("2024-01-15"),
    number: 20,
    status: 1,
  },
  {
    id: 14,
    courseName: "Business Communication",
    teacherName: "Nguyen Van N",
    createDate: new Date("2024-02-18"),
    number: 16,
    status: 0,
  },
  {
    id: 15,
    courseName: "Academic Writing",
    teacherName: "Tran Thi O",
    createDate: new Date("2024-03-05"),
    number: 19,
    status: 1,
  },
  {
    id: 16,
    courseName: "English for Professionals",
    teacherName: "Le Van P",
    createDate: new Date("2024-04-12"),
    number: 21,
    status: 1,
  },
  {
    id: 17,
    courseName: "IELTS Class E",
    teacherName: "Nguyen Van Q",
    createDate: new Date("2024-05-01"),
    number: 24,
    status: 1,
  },
  {
    id: 18,
    courseName: "TOEIC Class C",
    teacherName: "Vo Thi R",
    createDate: new Date("2024-06-05"),
    number: 13,
    status: 0,
  },
  {
    id: 19,
    courseName: "General English",
    teacherName: "Nguyen Van S",
    createDate: new Date("2024-07-11"),
    number: 26,
    status: 1,
  },
  {
    id: 20,
    courseName: "English for Travel",
    teacherName: "Tran Van T",
    createDate: new Date("2024-08-19"),
    number: 14,
    status: 1,
  },
];
export const courseTeacherData = [
  {
    id: 1,
    courseName: "Ielts A",
    startDate: new Date("2023-01-15"),
    endDate: new Date("2023-01-15"),
    time: [
      {
        day: "Thu",
        startTime: "18:00",
        endTime: "21:00",
      },
      {
        day: "Tue",
        startTime: "18:00",
        endTime: "21:00",
      },
    ],
    number: 20,
    status: 1,
  },
  {
    id: 2,
    courseName: "Ielts A",
    startDate: new Date("2023-02-01"),
    endDate: new Date("2023-03-15"),
    time: [
      {
        day: "Mon",
        startTime: "08:30",
        endTime: "11:30",
      },
      {
        day: "Wed",
        startTime: "14:00",
        endTime: "17:00",
      },
    ],
    number: 25,
    status: 1,
  },
  {
    id: 3,
    courseName: "Ielts A",
    startDate: new Date("2023-04-10"),
    endDate: new Date("2023-05-20"),
    time: [
      {
        day: "Sat",
        startTime: "09:00",
        endTime: "12:00",
      },
      {
        day: "Sun",
        startTime: "10:00",
        endTime: "13:00",
      },
    ],
    number: 30,
    status: 0,
  },
  {
    id: 4,
    courseName: "Ielts A",
    startDate: new Date("2023-03-10"),
    endDate: new Date("2023-04-15"),
    time: [
      {
        day: "Wed",
        startTime: "13:00",
        endTime: "16:00",
      },
      {
        day: "Fri",
        startTime: "16:00",
        endTime: "19:00",
      },
    ],
    number: 22,
    status: 1,
  },
  {
    id: 5,
    courseName: "Ielts A",
    startDate: new Date("2023-05-10"),
    endDate: new Date("2023-06-20"),
    time: [
      {
        day: "Tue",
        startTime: "10:00",
        endTime: "12:00",
      },
      {
        day: "Thu",
        startTime: "14:00",
        endTime: "16:00",
      },
    ],
    number: 28,
    status: 0,
  },
  {
    id: 6,
    courseName: "Ielts A",
    startDate: new Date("2023-07-01"),
    endDate: new Date("2023-08-15"),
    time: [
      {
        day: "Mon",
        startTime: "09:30",
        endTime: "12:30",
      },
      {
        day: "Thu",
        startTime: "13:00",
        endTime: "16:00",
      },
    ],
    number: 35,
    status: 1,
  },
  {
    id: 7,
    courseName: "Ielts A",
    startDate: new Date("2023-06-01"),
    endDate: new Date("2023-07-10"),
    time: [
      {
        day: "Tue",
        startTime: "15:00",
        endTime: "18:00",
      },
      {
        day: "Thu",
        startTime: "11:00",
        endTime: "14:00",
      },
    ],
    number: 18,
    status: 1,
  },
  {
    id: 8,
    courseName: "Ielts A",
    startDate: new Date("2023-08-01"),
    endDate: new Date("2023-09-10"),
    time: [
      {
        day: "Sat",
        startTime: "08:00",
        endTime: "11:00",
      },
      {
        day: "Sun",
        startTime: "09:00",
        endTime: "12:00",
      },
    ],
    number: 24,
    status: 0,
  },
  {
    id: 9,
    courseName: "Ielts A",
    startDate: new Date("2023-09-10"),
    endDate: new Date("2023-10-15"),
    time: [
      {
        day: "Mon",
        startTime: "08:00",
        endTime: "10:00",
      },
      {
        day: "Wed",
        startTime: "10:00",
        endTime: "12:00",
      },
    ],
    number: 20,
    status: 1,
  },
  {
    id: 10,
    courseName: "Ielts A",
    startDate: new Date("2023-10-05"),
    endDate: new Date("2023-11-10"),
    time: [
      {
        day: "Fri",
        startTime: "09:00",
        endTime: "12:00",
      },
      {
        day: "Mon",
        startTime: "10:00",
        endTime: "13:00",
      },
    ],
    number: 32,
    status: 1,
  },
  {
    id: 11,
    courseName: "Ielts A",
    startDate: new Date("2023-12-01"),
    endDate: new Date("2023-12-20"),
    time: [
      {
        day: "Thu",
        startTime: "08:00",
        endTime: "11:00",
      },
      {
        day: "Sat",
        startTime: "12:00",
        endTime: "15:00",
      },
    ],
    number: 25,
    status: 1,
  },
  {
    id: 12,
    courseName: "Ielts A",
    startDate: new Date("2023-11-01"),
    endDate: new Date("2023-12-01"),
    time: [
      {
        day: "Wed",
        startTime: "13:00",
        endTime: "16:00",
      },
      {
        day: "Fri",
        startTime: "10:00",
        endTime: "13:00",
      },
    ],
    number: 30,
    status: 0,
  },
];

export const SingleCourseTeacherData = [
  {
    id: 1,
    birthday: new Date("2023-11-01"),
    studentName: "Nguyen Van A",
    enrolled: new Date("2023-11-01"),
    phone: "01234566666",
    gmail: "abc@gmail.com",
    status: 1,
  },
  {
    id: 2,
    birthday: new Date("2023-11-01"),
    studentName: "Tran Thi B",
    enrolled: new Date("2023-10-15"),
    phone: "01234577777",
    gmail: "def@gmail.com",
    status: 1,
  },
  {
    id: 3,
    birthday: new Date("2023-11-01"),
    studentName: "Le Van C",
    enrolled: new Date("2023-09-20"),
    phone: "01234588888",
    gmail: "ghi@gmail.com",
    status: 0,
  },
  {
    id: 4,
    birthday: new Date("2023-11-01"),
    studentName: "Pham Thi D",
    enrolled: new Date("2023-08-30"),
    phone: "01234599999",
    gmail: "jkl@gmail.com",
    status: 1,
  },
  {
    id: 5,
    birthday: new Date("2023-11-01"),
    studentName: "Ngo Van E",
    enrolled: new Date("2023-07-25"),
    phone: "01234600000",
    gmail: "mno@gmail.com",
    status: 0,
  },
  {
    id: 6,
    birthday: new Date("2023-11-01"),
    studentName: "Hoang Thi F",
    enrolled: new Date("2023-06-10"),
    phone: "01234611111",
    gmail: "pqr@gmail.com",
    status: 1,
  },
  {
    id: 7,
    birthday: new Date("2023-11-01"),
    studentName: "Vu Van G",
    enrolled: new Date("2023-05-05"),
    phone: "01234622222",
    gmail: "stu@gmail.com",
    status: 0,
  },
  {
    id: 8,
    birthday: new Date("2023-11-01"),
    studentName: "Nguyen Thi H",
    enrolled: new Date("2023-04-15"),
    phone: "01234633333",
    gmail: "vwx@gmail.com",
    status: 1,
  },
  {
    id: 9,
    birthday: new Date("2023-11-01"),
    studentName: "Truong Van I",
    enrolled: new Date("2023-03-01"),
    phone: "01234644444",
    gmail: "yz@gmail.com",
    status: 1,
  },
  {
    id: 10,
    birthday: new Date("2023-11-01"),
    studentName: "Phan Thi J",
    enrolled: new Date("2023-02-18"),
    phone: "01234655555",
    gmail: "abcde@gmail.com",
    status: 0,
  },
  {
    id: 11,
    birthday: new Date("2023-11-01"),
    studentName: "Nguyen Van K",
    enrolled: new Date("2023-01-22"),
    phone: "01234666666",
    gmail: "fghij@gmail.com",
    status: 1,
  },
  {
    id: 12,
    birthday: new Date("2023-11-01"),
    studentName: "Le Thi L",
    enrolled: new Date("2023-11-10"),
    phone: "01234677777",
    gmail: "klmno@gmail.com",
    status: 1,
  },
];

export const AssignmentsData = [
  {
    id: 1,
    img: "https://i.pinimg.com/564x/57/ae/bb/57aebb3dd772819e1eee6a1ee955e3a1.jpg",
    className: "ILE6.A-D240W",
    session: "Session 21 Unit 7",
    startDate: new Date("2023-11-01"),
    endDate: new Date("2023-12-01"),
    quatity: 20,
  },
  {
    id: 2,
    img: "https://i.pinimg.com/564x/57/ae/bb/57aebb3dd772819e1eee6a1ee955e3a1.jpg",
    className: "ILE6.B-D240X",
    session: "Session 22 Unit 8",
    startDate: new Date("2023-11-05"),
    endDate: new Date("2023-12-05"),
    quatity: 18,
  },
  {
    id: 3,
    img: "https://i.pinimg.com/564x/57/ae/bb/57aebb3dd772819e1eee6a1ee955e3a1.jpg",
    className: "ILE7.A-D241W",
    session: "Session 23 Unit 9",
    startDate: new Date("2023-12-01"),
    endDate: new Date("2024-01-01"),
    quatity: 25,
  },
  {
    id: 4,
    img: "https://i.pinimg.com/564x/57/ae/bb/57aebb3dd772819e1eee6a1ee955e3a1.jpg",
    className: "ILE7.B-D241X",
    session: "Session 24 Unit 10",
    startDate: new Date("2023-12-10"),
    endDate: new Date("2024-01-10"),
    quatity: 22,
  },
  {
    id: 5,
    img: "https://i.pinimg.com/564x/57/ae/bb/57aebb3dd772819e1eee6a1ee955e3a1.jpg",
    className: "ILE8.A-D242W",
    session: "Session 25 Unit 11",
    startDate: new Date("2024-01-05"),
    endDate: new Date("2024-02-05"),
    quatity: 19,
  },
  {
    id: 6,
    img: "https://i.pinimg.com/564x/57/ae/bb/57aebb3dd772819e1eee6a1ee955e3a1.jpg",
    className: "ILE8.B-D242X",
    session: "Session 26 Unit 12",
    startDate: new Date("2024-01-15"),
    endDate: new Date("2024-02-15"),
    quatity: 21,
  },
  {
    id: 7,
    img: "https://i.pinimg.com/564x/57/ae/bb/57aebb3dd772819e1eee6a1ee955e3a1.jpg",
    className: "ILE9.A-D243W",
    session: "Session 27 Unit 13",
    startDate: new Date("2024-02-01"),
    endDate: new Date("2024-03-01"),
    quatity: 20,
  },
];
export const GradingData = [
  {
    id: 1,
    studentName: "Vu Ho Quynh Anh",
    test: [
      {
        id: 1,
        reading: 9.5,
        listening: 9.5,
      },
      {
        id: 2,
        reading: 9.5,
        listening: 9.5,
      },
    ],
  },
  {
    id: 2,
    studentName: "Nguyen Van A",
    test: [
      {
        id: 1,
        reading: 8.0,
        listening: 8.5,
      },
      {
        id: 2,
        reading: 8.2,
        listening: 8.7,
      },
    ],
  },
  {
    id: 3,
    studentName: "Tran Thi B",
    test: [
      {
        id: 1,
        reading: 7.5,
        listening: 7.8,
      },
      {
        id: 2,
        reading: 8.0,
        listening: 8.1,
      },
    ],
  },
  {
    id: 4,
    studentName: "Le Minh C",
    test: [
      {
        id: 1,
        reading: 6.5,
        listening: 7.0,
      },
      {
        id: 2,
        reading: 7.2,
        listening: 7.5,
      },
    ],
  },
  {
    id: 5,
    studentName: "Pham Van D",
    test: [
      {
        id: 1,
        reading: 9.0,
        listening: 9.0,
      },
      {
        id: 2,
        reading: 9.2,
        listening: 9.4,
      },
    ],
  },
  {
    id: 6,
    studentName: "Hoang Thi E",
    test: [
      {
        id: 1,
        reading: 8.5,
        listening: 8.8,
      },
      {
        id: 2,
        reading: 8.7,
        listening: 8.9,
      },
    ],
  },
];

export const ViewAssignmentData = [
  {
    id: 1,
    studentName: "Vu Ho Quynh Anh",
    assignment: "Exercise_1.doc",
    history: [
      {
        id: 1,
        atTime: new Date("2023-11-01"),
      },
      {
        id: 2,
        atTime: new Date("2023-11-01"),
      },
      {
        id: 3,
        atTime: new Date("2023-11-01"),
      },
    ],
  },
];

export const ScoringAssignmentData = [
  {
    id: 1,
    studentName: "Vu Ho Quynh Anh",
    assignment: "Exercise_1.doc",
    history: [
      {
        id: 1,
        atTime: new Date("2023-11-01"),
      },
      {
        id: 2,
        atTime: new Date("2023-11-01"),
      },
      {
        id: 3,
        atTime: new Date("2023-11-01"),
      },
    ],
  },
  {
    id: 2,
    studentName: "Nguyen Thanh Long",
    assignment: "Exercise_2.pdf",
    history: [
      {
        id: 1,
        atTime: new Date("2023-11-02"),
      },
      {
        id: 2,
        atTime: new Date("2023-11-03"),
      },
    ],
  },
  {
    id: 3,
    studentName: "Tran Minh Tuan",
    assignment: "Project_Report.docx",
    history: [
      {
        id: 1,
        atTime: new Date("2023-11-03"),
      },
    ],
  },
  {
    id: 4,
    studentName: "Le Thi Bao Chau",
    assignment: "Homework_Sheet.xlsx",
    history: [
      {
        id: 1,
        atTime: new Date("2023-11-04"),
      },
      {
        id: 2,
        atTime: new Date("2023-11-05"),
      },
    ],
  },
  {
    id: 5,
    studentName: "Pham Duc Manh",
    assignment: "Final_Project.pptx",
    history: [
      {
        id: 1,
        atTime: new Date("2023-11-01"),
      },
      {
        id: 2,
        atTime: new Date("2023-11-02"),
      },
      {
        id: 3,
        atTime: new Date("2023-11-03"),
      },
    ],
  },
];

export const CourseStudentData = [
  {
    id: 1,
    img: "https://i.pinimg.com/564x/57/ae/bb/57aebb3dd772819e1eee6a1ee955e3a1.jpg",
    className: "IELTS 6+",
    startDate: new Date("2024-06-30"),
    endDate: new Date("2024-12-30"),
    address: "Le Trong Tan Street, Son Ky, Tan Phu District",
  },
  {
    id: 2,
    img: "https://i.pinimg.com/564x/57/ae/bb/57aebb3dd772819e1eee6a1ee955e3a1.jpg",
    className: "TOEIC Advanced",
    startDate: new Date("2024-07-01"),
    endDate: new Date("2024-12-01"),
    address: "Nguyen Van Linh Street, District 7, HCMC",
  },
  {
    id: 3,
    img: "https://i.pinimg.com/564x/57/ae/bb/57aebb3dd772819e1eee6a1ee955e3a1.jpg",
    className: "Business English",
    startDate: new Date("2024-08-15"),
    endDate: new Date("2025-02-15"),
    address: "Hai Ba Trung Street, District 1, HCMC",
  },
  {
    id: 4,
    img: "https://i.pinimg.com/564x/57/ae/bb/57aebb3dd772819e1eee6a1ee955e3a1.jpg",
    className: "General English for Beginners",
    startDate: new Date("2024-09-10"),
    endDate: new Date("2025-03-10"),
    address: "Pham Van Dong Street, Thu Duc City, HCMC",
  },
  {
    id: 5,
    img: "https://i.pinimg.com/564x/57/ae/bb/57aebb3dd772819e1eee6a1ee955e3a1.jpg",
    className: "IELTS Intensive",
    startDate: new Date("2024-07-20"),
    endDate: new Date("2025-01-20"),
    address: "Tran Hung Dao Street, District 5, HCMC",
  },
  {
    id: 6,
    img: "https://i.pinimg.com/564x/57/ae/bb/57aebb3dd772819e1eee6a1ee955e3a1.jpg",
    className: "TOEFL Preparation",
    startDate: new Date("2024-10-05"),
    endDate: new Date("2025-04-05"),
    address: "Cach Mang Thang 8 Street, District 10, HCMC",
  },
  {
    id: 7,
    img: "https://i.pinimg.com/564x/57/ae/bb/57aebb3dd772819e1eee6a1ee955e3a1.jpg",
    className: "English for Kids",
    startDate: new Date("2024-11-01"),
    endDate: new Date("2025-05-01"),
    address: "Quang Trung Street, Go Vap District, HCMC",
  },
  {
    id: 8,
    img: "https://i.pinimg.com/564x/57/ae/bb/57aebb3dd772819e1eee6a1ee955e3a1.jpg",
    className: "Speaking Mastery",
    startDate: new Date("2024-12-12"),
    endDate: new Date("2025-06-12"),
    address: "Ba Thang Hai Street, District 10, HCMC",
  },
  {
    id: 9,
    img: "https://i.pinimg.com/564x/57/ae/bb/57aebb3dd772819e1eee6a1ee955e3a1.jpg",
    className: "Listening Skills Improvement",
    startDate: new Date("2024-08-01"),
    endDate: new Date("2025-02-01"),
    address: "Pasteur Street, District 3, HCMC",
  },
];

import { TeacherCourse } from "@/types/pagination";

export const teacherData: TeacherCourse[] = [
  {
    teacher: {
      id: "1",
      name: "John Smith",
      birth: new Date("1985-06-15"),
      email: "john.smith@example.com",
      phone: "+123456789",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "123 Main St",
        city: "New York",
        country: "USA",
      },
      more: "Experienced in teaching English and Business Communication.",
    },
    course: {
      id: "1",
      name: "Advanced English Grammar",
    },
    joinDate: new Date("2022-01-10"),
    kindJob: "Full-time",
    description:
      "Teaching advanced grammar concepts to improve students' written and spoken English.",
    earning: 5000,
    point: 4.8,
    status: "Active",
  },
  {
    teacher: {
      id: "1", // John Smith
      name: "John Smith",
      birth: new Date("1985-06-15"),
      email: "john.smith@example.com",
      phone: "+123456789",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "123 Main St",
        city: "New York",
        country: "USA",
      },
      more: "Experienced in teaching English and Business Communication.",
    },
    course: {
      id: "2",
      name: "Business Communication Skills",
    },
    joinDate: new Date("2022-02-01"),
    kindJob: "Full-time",
    description: "Focusing on effective communication in business contexts.",
    earning: 5000,
    point: 4.8,
    status: "Active",
  },
  {
    teacher: {
      id: "2",
      name: "Emily Johnson",
      birth: new Date("1990-09-25"),
      email: "emily.johnson@example.com",
      phone: "+987654321",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "456 Oak Ave",
        city: "Los Angeles",
        country: "USA",
      },
      more: "Specializes in teaching IELTS and TOEFL preparation courses.",
    },
    course: {
      id: "3",
      name: "IELTS Preparation",
    },
    joinDate: new Date("2021-05-15"),
    kindJob: "Part-time",
    description: "Guiding students through IELTS exam strategies.",
    earning: 3000,
    point: 4.9,
    status: "Active",
  },
  {
    teacher: {
      id: "2", // Emily Johnson
      name: "Emily Johnson",
      birth: new Date("1990-09-25"),
      email: "emily.johnson@example.com",
      phone: "+987654321",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "456 Oak Ave",
        city: "Los Angeles",
        country: "USA",
      },
      more: "Specializes in teaching IELTS and TOEFL preparation courses.",
    },
    course: {
      id: "4",
      name: "TOEFL Preparation",
    },
    joinDate: new Date("2021-06-15"),
    kindJob: "Part-time",
    description: "Helping students prepare for the TOEFL exam.",
    earning: 3000,
    point: 4.9,
    status: "Active",
  },
  {
    teacher: {
      id: "3",
      name: "Michael Brown",
      birth: new Date("1978-12-05"),
      email: "michael.brown@example.com",
      phone: "+1122334455",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "789 Pine Rd",
        city: "Chicago",
        country: "USA",
      },
      more: "Over 20 years of experience in teaching Business English.",
    },
    course: {
      id: "5",
      name: "Business English Communication",
    },
    joinDate: new Date("2020-03-22"),
    kindJob: "Full-time",
    description: "Teaching professional English communication skills.",
    earning: 6000,
    point: 4.7,
    status: "Active",
  },
  {
    teacher: {
      id: "3",
      name: "Michael Brown",
      birth: new Date("1978-12-05"),
      email: "michael.brown@example.com",
      phone: "+1122334455",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "789 Pine Rd",
        city: "Chicago",
        country: "USA",
      },
      more: "Over 20 years of experience in teaching Business English.",
    },
    course: {
      id: "6",
      name: "Negotiation Skills in English",
    },
    joinDate: new Date("2020-04-01"),
    kindJob: "Full-time",
    description: "Teaching negotiation tactics and skills in English.",
    earning: 6000,
    point: 4.7,
    status: "Active",
  },
  {
    teacher: {
      id: "4",
      name: "Sarah White",
      birth: new Date("1982-11-19"),
      email: "sarah.white@example.com",
      phone: "+2233445566",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "321 Birch Blvd",
        city: "Houston",
        country: "USA",
      },
      more: "Expert in teaching conversational English and pronunciation.",
    },
    course: {
      id: "7",
      name: "English Pronunciation Mastery",
    },
    joinDate: new Date("2023-07-01"),
    kindJob: "Contract",
    description:
      "Helping students achieve clear and accurate English pronunciation.",
    earning: 4000,
    point: 4.6,
    status: "Active",
  },
  {
    teacher: {
      id: "4", // Sarah White
      name: "Sarah White",
      birth: new Date("1982-11-19"),
      email: "sarah.white@example.com",
      phone: "+2233445566",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "321 Birch Blvd",
        city: "Houston",
        country: "USA",
      },
      more: "Expert in teaching conversational English and pronunciation.",
    },
    course: {
      id: "8",
      name: "Conversational English Skills",
    },
    joinDate: new Date("2023-08-01"),
    kindJob: "Contract",
    description:
      "Enhancing students' ability to communicate effectively in English.",
    earning: 4000,
    point: 4.6,
    status: "Active",
  },
  {
    teacher: {
      id: "5",
      name: "David Lee",
      birth: new Date("1995-03-08"),
      email: "david.lee@example.com",
      phone: "+3344556677",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "654 Maple St",
        city: "San Francisco",
        country: "USA",
      },
      more: "Focused on teaching online courses for beginners.",
    },
    course: {
      id: "9",
      name: "Basic English for Beginners",
    },
    joinDate: new Date("2022-10-05"),
    kindJob: "Part-time",
    description: "Teaching foundational English skills.",
    earning: 2500,
    point: 4.5,
    status: "Active",
  },
  {
    teacher: {
      id: "5", // David Lee
      name: "David Lee",
      birth: new Date("1995-03-08"),
      email: "david.lee@example.com",
      phone: "+3344556677",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "654 Maple St",
        city: "San Francisco",
        country: "USA",
      },
      more: "Focused on teaching online courses for beginners.",
    },
    course: {
      id: "10",
      name: "English for Kids",
    },
    joinDate: new Date("2022-11-01"),
    kindJob: "Part-time",
    description: "Teaching English to children using fun and engaging methods.",
    earning: 2500,
    point: 4.5,
    status: "Active",
  },
];

export const teacherDataTable = [
  {
    teacher: {
      id: "1",
      name: "John Smith",
      birth: new Date("1985-06-15"),
      email: "john.smith@example.com",
      phone: "+123456789",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "123 Main St",
        city: "New York",
        country: "USA",
      },
      more: "Experienced in teaching English and Business Communication.",
    },
    course: 2,
    joinDate: new Date("2022-01-10"),
    earning: 5000,
    point: 4.8,
    status: "Active",
  },
  {
    teacher: {
      id: "2",
      name: "Emily Johnson",
      birth: new Date("1990-09-25"),
      email: "emily.johnson@example.com",
      phone: "+987654321",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "456 Oak Ave",
        city: "Los Angeles",
        country: "USA",
      },
      more: "Specializes in teaching IELTS and TOEFL preparation courses.",
    },
    course: 2,
    joinDate: new Date("2021-05-15"),
    earning: 3000,
    point: 4.9,
    status: "Active",
  },
  {
    teacher: {
      id: "3",
      name: "Michael Brown",
      birth: new Date("1978-12-05"),
      email: "michael.brown@example.com",
      phone: "+1122334455",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "789 Pine Rd",
        city: "Chicago",
        country: "USA",
      },
      more: "Over 20 years of experience in teaching Business English.",
    },
    course: 2,
    joinDate: new Date("2020-03-22"),
    earning: 6000,
    point: 4.7,
    status: "Active",
  },
  {
    teacher: {
      id: "4",
      name: "Sarah White",
      birth: new Date("1982-11-19"),
      email: "sarah.white@example.com",
      phone: "+2233445566",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "321 Birch Blvd",
        city: "Houston",
        country: "USA",
      },
      more: "Expert in teaching conversational English and pronunciation.",
    },
    course: 2,
    joinDate: new Date("2023-07-01"),
    earning: 4000,
    point: 4.6,
    status: "Active",
  },
  {
    teacher: {
      id: "5", // David Lee
      name: "David Lee",
      birth: new Date("1995-03-08"),
      email: "david.lee@example.com",
      phone: "+3344556677",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "654 Maple St",
        city: "San Francisco",
        country: "USA",
      },
      more: "Focused on teaching online courses for beginners.",
    },
    course: 2,
    joinDate: new Date("2022-11-01"),
    earning: 2500,
    point: 4.5,
    status: "Active",
  },
  {
    teacher: {
      id: "6", // David Lee
      name: "David Lee",
      birth: new Date("1995-03-08"),
      email: "david.lee@example.com",
      phone: "+3344556677",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "654 Maple St",
        city: "San Francisco",
        country: "USA",
      },
      more: "Focused on teaching online courses for beginners.",
    },
    course: 2,
    joinDate: new Date("2022-11-01"),
    earning: 2500,
    point: 4.5,
    status: "Active",
  },
  {
    teacher: {
      id: "7",
      name: "John Smith",
      birth: new Date("1985-06-15"),
      email: "john.smith@example.com",
      phone: "+123456789",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "123 Main St",
        city: "New York",
        country: "USA",
      },
      more: "Experienced in teaching English and Business Communication.",
    },
    course: 2,
    joinDate: new Date("2022-01-10"),
    earning: 5000,
    point: 4.8,
    status: "Active",
  },
  {
    teacher: {
      id: "8",
      name: "Emily Johnson",
      birth: new Date("1990-09-25"),
      email: "emily.johnson@example.com",
      phone: "+987654321",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "456 Oak Ave",
        city: "Los Angeles",
        country: "USA",
      },
      more: "Specializes in teaching IELTS and TOEFL preparation courses.",
    },
    course: 2,
    joinDate: new Date("2021-05-15"),
    earning: 3000,
    point: 4.9,
    status: "Active",
  },
  {
    teacher: {
      id: "9",
      name: "Michael Brown",
      birth: new Date("1978-12-05"),
      email: "michael.brown@example.com",
      phone: "+1122334455",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "789 Pine Rd",
        city: "Chicago",
        country: "USA",
      },
      more: "Over 20 years of experience in teaching Business English.",
    },
    course: 2,
    joinDate: new Date("2020-03-22"),
    earning: 6000,
    point: 4.7,
    status: "Active",
  },
  {
    teacher: {
      id: "10",
      name: "Sarah White",
      birth: new Date("1982-11-19"),
      email: "sarah.white@example.com",
      phone: "+2233445566",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "321 Birch Blvd",
        city: "Houston",
        country: "USA",
      },
      more: "Expert in teaching conversational English and pronunciation.",
    },
    course: 2,
    joinDate: new Date("2023-07-01"),
    earning: 4000,
    point: 4.6,
    status: "Active",
  },
  {
    teacher: {
      id: "11", // David Lee
      name: "David Lee",
      birth: new Date("1995-03-08"),
      email: "david.lee@example.com",
      phone: "+3344556677",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "654 Maple St",
        city: "San Francisco",
        country: "USA",
      },
      more: "Focused on teaching online courses for beginners.",
    },
    course: 2,
    joinDate: new Date("2022-11-01"),
    earning: 2500,
    point: 4.5,
    status: "Active",
  },
  {
    teacher: {
      id: "12", // David Lee
      name: "David Lee",
      birth: new Date("1995-03-08"),
      email: "david.lee@example.com",
      phone: "+3344556677",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "654 Maple St",
        city: "San Francisco",
        country: "USA",
      },
      more: "Focused on teaching online courses for beginners.",
    },
    course: 2,
    joinDate: new Date("2022-11-01"),
    earning: 2500,
    point: 4.5,
    status: "Active",
  },
  {
    teacher: {
      id: "13",
      name: "John Smith",
      birth: new Date("1985-06-15"),
      email: "john.smith@example.com",
      phone: "+123456789",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "123 Main St",
        city: "New York",
        country: "USA",
      },
      more: "Experienced in teaching English and Business Communication.",
    },
    course: 2,
    joinDate: new Date("2022-01-10"),
    earning: 5000,
    point: 4.8,
    status: "Active",
  },
  {
    teacher: {
      id: "14",
      name: "Emily Johnson",
      birth: new Date("1990-09-25"),
      email: "emily.johnson@example.com",
      phone: "+987654321",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "456 Oak Ave",
        city: "Los Angeles",
        country: "USA",
      },
      more: "Specializes in teaching IELTS and TOEFL preparation courses.",
    },
    course: 2,
    joinDate: new Date("2021-05-15"),
    earning: 3000,
    point: 4.9,
    status: "Active",
  },
  {
    teacher: {
      id: "15",
      name: "Michael Brown",
      birth: new Date("1978-12-05"),
      email: "michael.brown@example.com",
      phone: "+1122334455",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "789 Pine Rd",
        city: "Chicago",
        country: "USA",
      },
      more: "Over 20 years of experience in teaching Business English.",
    },
    course: 2,
    joinDate: new Date("2020-03-22"),
    earning: 6000,
    point: 4.7,
    status: "Active",
  },
  {
    teacher: {
      id: "16",
      name: "Sarah White",
      birth: new Date("1982-11-19"),
      email: "sarah.white@example.com",
      phone: "+2233445566",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "321 Birch Blvd",
        city: "Houston",
        country: "USA",
      },
      more: "Expert in teaching conversational English and pronunciation.",
    },
    course: 2,
    joinDate: new Date("2023-07-01"),
    earning: 4000,
    point: 4.6,
    status: "Active",
  },
  {
    teacher: {
      id: "17", // David Lee
      name: "David Lee",
      birth: new Date("1995-03-08"),
      email: "david.lee@example.com",
      phone: "+3344556677",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "654 Maple St",
        city: "San Francisco",
        country: "USA",
      },
      more: "Focused on teaching online courses for beginners.",
    },
    course: 2,
    joinDate: new Date("2022-11-01"),
    earning: 2500,
    point: 4.5,
    status: "Active",
  },
  {
    teacher: {
      id: "18", // David Lee
      name: "David Lee",
      birth: new Date("1995-03-08"),
      email: "david.lee@example.com",
      phone: "+3344556677",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "654 Maple St",
        city: "San Francisco",
        country: "USA",
      },
      more: "Focused on teaching online courses for beginners.",
    },
    course: 2,
    joinDate: new Date("2022-11-01"),
    earning: 2500,
    point: 4.5,
    status: "Active",
  },
  {
    teacher: {
      id: "19",
      name: "John Smith",
      birth: new Date("1985-06-15"),
      email: "john.smith@example.com",
      phone: "+123456789",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "123 Main St",
        city: "New York",
        country: "USA",
      },
      more: "Experienced in teaching English and Business Communication.",
    },
    course: 2,
    joinDate: new Date("2022-01-10"),
    earning: 5000,
    point: 4.8,
    status: "Active",
  },
  {
    teacher: {
      id: "20",
      name: "Emily Johnson",
      birth: new Date("1990-09-25"),
      email: "emily.johnson@example.com",
      phone: "+987654321",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "456 Oak Ave",
        city: "Los Angeles",
        country: "USA",
      },
      more: "Specializes in teaching IELTS and TOEFL preparation courses.",
    },
    course: 2,
    joinDate: new Date("2021-05-15"),
    earning: 3000,
    point: 4.9,
    status: "Active",
  },
  {
    teacher: {
      id: "21",
      name: "Michael Brown",
      birth: new Date("1978-12-05"),
      email: "michael.brown@example.com",
      phone: "+1122334455",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "789 Pine Rd",
        city: "Chicago",
        country: "USA",
      },
      more: "Over 20 years of experience in teaching Business English.",
    },
    course: 2,
    joinDate: new Date("2020-03-22"),
    earning: 6000,
    point: 4.7,
    status: "Active",
  },
  {
    teacher: {
      id: "22",
      name: "Sarah White",
      birth: new Date("1982-11-19"),
      email: "sarah.white@example.com",
      phone: "+2233445566",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "321 Birch Blvd",
        city: "Houston",
        country: "USA",
      },
      more: "Expert in teaching conversational English and pronunciation.",
    },
    course: 2,
    joinDate: new Date("2023-07-01"),
    earning: 4000,
    point: 4.6,
    status: "Active",
  },
  {
    teacher: {
      id: "23", // David Lee
      name: "David Lee",
      birth: new Date("1995-03-08"),
      email: "david.lee@example.com",
      phone: "+3344556677",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "654 Maple St",
        city: "San Francisco",
        country: "USA",
      },
      more: "Focused on teaching online courses for beginners.",
    },
    course: 2,
    joinDate: new Date("2022-11-01"),
    earning: 2500,
    point: 4.5,
    status: "Active",
  },
  {
    teacher: {
      id: "24", // David Lee
      name: "David Lee",
      birth: new Date("1995-03-08"),
      email: "david.lee@example.com",
      phone: "+3344556677",
      ava: "/assets/images/wenjun-lin-.jpg",
      address: {
        street: "654 Maple St",
        city: "San Francisco",
        country: "USA",
      },
      more: "Focused on teaching online courses for beginners.",
    },
    course: 2,
    joinDate: new Date("2022-11-01"),
    earning: 2500,
    point: 4.5,
    status: "Active",
  },
];
