const users = [
  {
    userId: "1",
    username: "huynh123",
    fullname: "Huỳnh",
    numberphone: "0987654321",
    email: "huynh@example.com",
    birthday: new Date("1995-07-21"),
    gender: "male",
    password: "encryptedpassword123", // Password này cần được mã hóa
    avatar: "/assets/images/62ceabe8a02e045a0793ec431098bcc1.jpg",
    background: "/assets/images/62ceabe8a02e045a0793ec431098bcc1.jpg",
    address: "Hồ Chí Minh, Việt Nam",
    job: "Kỹ sư phần mềm",
    hobbies: ["Ăn uống", "Chơi game"],
    bio: "Là một người yêu công nghệ và ẩm thực.",
    nickName: "Huy",
    friends: ["2", "3", "4"],
    bestFriends: ["3"],
    following: ["2", "3", "4", "5"],
    block: [],
    isAdmin: false,
  },
  {
    userId: "2",
    username: "minh456",
    fullname: "Minh",
    numberphone: "0987654322",
    email: "minh@example.com",
    birthday: new Date("1990-01-15"),
    gender: "male",
    password: "encryptedpassword456", // Password này cần được mã hóa
    avatar: "/assets/images/62ceabe8a02e045a0793ec431098bcc1.jpg",
    background: "/assets/images/62ceabe8a02e045a0793ec431098bcc1.jpg",
    address: "Hà Nội, Việt Nam",
    job: "Nhà phát triển web",
    hobbies: ["Chụp ảnh", "Đọc sách"],
    bio: "Thích tìm hiểu về các xu hướng công nghệ mới.",
    nickName: "M",
    friends: ["1", "3", "4"],
    bestFriends: ["4"],
    following: ["1", "4", "5"],
    block: [],
    isAdmin: false,
  },
  {
    userId: "3",
    username: "anh789",
    fullname: "Anh",
    numberphone: "0987654323",
    email: "anh@example.com",
    birthday: new Date("1998-11-02"),
    gender: "female",
    password: "encryptedpassword789", // Password này cần được mã hóa
    avatar: "/assets/images/62ceabe8a02e045a0793ec431098bcc1.jpg",
    background: "/assets/images/62ceabe8a02e045a0793ec431098bcc1.jpg",
    address: "Đà Nẵng, Việt Nam",
    job: "Thiết kế đồ họa",
    hobbies: ["Vẽ", "Du lịch"],
    bio: "Một nhà thiết kế sáng tạo yêu thích cái đẹp.",
    nickName: "An",
    friends: ["1", "2", "4"],
    bestFriends: ["1"],
    following: ["1", "2", "5"],
    block: [],
    isAdmin: false,
  },
  {
    userId: "4",
    username: "thao999",
    fullname: "Thảo",
    numberphone: "0987654324",
    email: "thao@example.com",
    birthday: new Date("1996-09-08"),
    gender: "female",
    password: "encryptedpassword999", // Password này cần được mã hóa
    avatar: "/assets/images/62ceabe8a02e045a0793ec431098bcc1.jpg",
    background: "/assets/images/62ceabe8a02e045a0793ec431098bcc1.jpg",
    address: "Cần Thơ, Việt Nam",
    job: "Nhà báo",
    hobbies: ["Viết lách", "Nấu ăn"],
    bio: "Một người yêu thích ẩm thực và viết về cuộc sống.",
    nickName: "T",
    friends: ["1", "2", "3"],
    bestFriends: ["2"],
    following: ["1", "3", "5"],
    block: [],
    isAdmin: false,
  },
  {
    userId: "5",
    username: "linh123",
    fullname: "Linh",
    numberphone: "0987654325",
    email: "linh@example.com",
    birthday: new Date("1992-12-10"),
    gender: "female",
    password: "encryptedpassword1234", // Password này cần được mã hóa
    avatar: "/assets/images/62ceabe8a02e045a0793ec431098bcc1.jpg",
    background: "/assets/images/62ceabe8a02e045a0793ec431098bcc1.jpg",
    address: "Bình Dương, Việt Nam",
    job: "Giáo viên",
    hobbies: ["Đọc sách", "Yoga"],
    bio: "Yêu thích chia sẻ kiến thức và rèn luyện sức khỏe.",
    nickName: "L",
    friends: ["1", "2", "3"],
    bestFriends: ["3"],
    following: ["1", "2", "4"],
    block: [],
    isAdmin: false,
  },
  {
    userId: "6",
    username: "nam456",
    fullname: "Nam",
    numberphone: "0987654326",
    email: "nam@example.com",
    birthday: new Date("1993-03-05"),
    gender: "male",
    password: "encryptedpassword567", // Password này cần được mã hóa
    avatar: "/assets/images/62ceabe8a02e045a0793ec431098bcc1.jpg",
    background: "/assets/images/62ceabe8a02e045a0793ec431098bcc1.jpg",
    address: "Hải Phòng, Việt Nam",
    job: "Lập trình viên",
    hobbies: ["Chơi bóng đá", "Lập trình"],
    bio: "Một lập trình viên với niềm đam mê về công nghệ.",
    nickName: "N",
    friends: ["1", "2", "4"],
    bestFriends: ["1"],
    following: ["1", "2", "3"],
    block: [],
    isAdmin: false,
  },
];

export default users;
